#mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    capitalMode: true
    banner: false
    db-config:
      id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
  type-handlers-package:  cn.shanxincd.plat.common.data.handler
  configuration:
    jdbc-type-for-null: 'null'
    call-setters-on-nulls: true