#!/bin/bash

#打包
mvn clean install
echo "###############Jar打包完成###############"

#Docker镜像打包
docker build -t
echo "###############Image打包完成###############"

#Docker镜像推送
docker push
echo "###############Image推送完成###############"

#调用[Rancher API]重新部署